<?php
const ERR_LAZY = 69;
const ERR_FORM_VALIDATION = 99;



/*appliction specific errors*/
const ERR_AUTHENTICATION_ERROR = 101;
const ERR_USER_ACCOUNT_SUSPENDED = 102;
const ERR_USER_ACCOUNT_NOT_MOBILE_VALIDATED = 103;
const ERR_USER_ACCOUNT_NOT_EMAIL_VALIDATED = 104;
const ERR_USER_ACCOUNT_INACTIVE = 105;

const INVALID_PASSKEY = 201;
const MOBILE_ALREADY_VALIDATED = 202;
const FLOOD_CONTROL = 203;
